# Site settings
title: Sparkplug - Your software development partners.
email: hello@sparkpl.ug
description: "Sparkplug works with organizations to build beautiful software through human centered design and agile execution."
baseurl: ""
url: "http://sparkpl.ug"

# Build settings
# markdown: kramdown
permalink: pretty

paginate: 4
