# Site settings
title: Sparkplug | Web Application Development | Technology Consulting
email: hello@sparkpl.ug
description: "Sparkplug uses open source technology to develop web and mobile applications, integrate with client teams, design interfaces and experiences, and consult on projects large & small."
baseurl: ""
url: "http://sparkpl.ug"

# Build settings
# markdown: kramdown
permalink: pretty

paginate: 4
