# Site settings
title: Sparkplug - Your software development partners
email: hello@sparkpl.ug
description: Sparkplug works with organizations to build great software through human-centered design and fervent execution. We are your software development partners.
baseurl: ""
url: "http://sparkpl.ug"

# Build settings
# markdown: kramdown
permalink: pretty

paginate: 4
